name: Deploy RestieAPI to VPS

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: list repo files
        run: |
          pwd
          ls -la
          echo "---- tree (top 3 levels) ----"
          find . -maxdepth 3 -type d -print
          echo "---- csproj files ----"
          find . -name "*.csproj" -print
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore RestieAPI/RestieAPI/RestieAPI.csproj

      - name: Publish
        run: dotnet publish RestieAPI/RestieAPI/RestieAPI.csproj -c Release -o publish

      - name: Configure SSH
        shell: bash
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "${{ secrets.VPS_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy (rsync)
        shell: bash
        run: |
          rsync -az --delete -e "ssh -i ~/.ssh/id_ed25519" \
            ./publish/ \
            "${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/myapi/"

      - name: Restart service
        shell: bash
        run: |
          ssh -i ~/.ssh/id_ed25519 "${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}" \
            "sudo -n /usr/local/bin/restart-restieapi"
